name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Sam Hum
api-version: 1.21
main: edu.whimc.overworld_agent.OverworldAgent
softdepend: [Citizens,ProtocolLib,WHIMC-ScienceTools,Journey,SpeechReceiver,HolographicDisplays,CoreProtect,WHIMC-StudentFeedback]
commands:
  agent:
    description: agent command for dialogue
    usage: '/agent'
  agents:
    description: Root agent admin command
    usage: '/agents'
  oacallback:
    description: Internal callback command for chat UI
    usage: '/oacallback <uuid>'
  admintags:
    description: Manage tags
    usage: '/admintags'
  assess-habitat:
    description: command to assess habitat
    usage: '/assess-habitat'